version: "3.1"

services:
  nifi:
    build:
      context: ./nifi
      dockerfile: ./Dockerfile
    image: psut/nifi
    container_name: psut_nifi
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/import:/opt/nifi/uploads
    networks:
      - localnet

  redis:
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    image: psut_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - localnet

  neo4j:
    build:
      context: ./neo4j
      dockerfile: ./Dockerfile
    image: psut/neo4j
    hostname: neo4j
    container_name: psut_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volumes/db:/data
      - ./volumes/logs:/logs
      - ./volumes/import:/var/lib/neo4j/import
      - ./volumes/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/test
    networks:
      - localnet

  jupyter:
    build:
      context: ./jupyter
      dockerfile: ./Dockerfile
    image: psut/jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./volumes/import:/home/jovyan/work/result
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "psut2021"
    ports:
      - "8888:8888"
    container_name: psut_jupyter
    links:
      - neo4j
    networks:
      - localnet

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: ./Dockerfile
    image: psut_eleasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./volumes/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - localnet

  kibana:
    build:
      context: ./kibana
      dockerfile: ./Dockerfile
    image: psut_kibana
    ports:
      - 5601:5601
    volumes:
      - ./volumes/esdata1:/usr/share/elasticsearch/data
    networks:
      - localnet

networks:
  localnet:
    attachable: true

